image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

discovery_test:
  image: python:3
  script:
    - python discovery_yaml_generator.py
    - cp discovery.yml $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - test
    except:
    - main

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main

discovery_pages:
  image: python:3
  script:
    - python discovery_yaml_generator.py
    - cp discovery.yml $CI_PROJECT_DIR/public/
  artifacts:
      paths:
      - test
  only:
    - main
