variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

stages:
  - discovery
  - test
  - deploy

##########################
# Jekyll Build
##########################

.jekyll_template: &jekyll_template
  image: ruby:2.7
  before_script:
    - bundle install

jekyll_test:
  <<: *jekyll_template
  stage: test
  needs:
    - job: discovery_test
      artifacts: true
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  <<: *jekyll_template
  stage: deploy
  needs:
    - job: discovery_gen
      artifacts: true
  script:
  - cp discovery/discovery.yml public
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main

##########################
# discovery.yml Generation
##########################

.discovery_template: &discovery_template
  image: python:3
  before_script:
    - pip install PyYAML

discovery_test:
  <<: *discovery_template
  stage: discovery
  script:
    - python discovery_yaml_generator.py
  artifacts:
    paths:
      - test
  except:
    - main

discovery_gen:
  <<: *discovery_template
  stage: discovery
  script:
    - python discovery_yaml_generator.py
    - mkdir .discovery
    - cp discovery.yml discovery
  artifacts:
      paths:
      - discovery
  only:
    - main
